apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionWebhook
metadata:
  name: session-validation
spec:
  clientConfig:
    service:
      name: ambient-webhook-service
      namespace: ambient-system
      path: "/validate-session"
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURIRENDQWdRQ0NRQzcwYnNIa0xmMldUQU5CZ2txaGtpRzl3MEJBUXNGQURCUU1Rc3dDUVlEVlFRR0V3SlYKVXpFTE1Ba0dBMVVFQ0F3Q1EwRXhDekFKQmdOVkJBY01BbE5HTVJJd0VBWURWUVFLREFsQmJXSnBaVzUwUVVreApFekFSQmdOVkJBTU1DbmRsWW1odmIyc3RZMkV3SGhjTk1qVXdPVEUwTWpFd09UUXhXaGNOTWpZd09URTBNakV3Ck9UUXhXakJRTVFzd0NRWURWUVFHRXdKVlV6RUxNQWtHQTFVRUNBd0NRMEV4Q3pBSkJnTlZCQWNNQWxOR01SSXcKRUFZRFZRUUtEQWxCYldKcFpXNTBRVWt4RXpBUkJnTlZCQU1NQ25kbFltaHZiMnN0WTJFd2dnRWlNQTBHQ1NxRwpTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFERjdBOWFTNDR4aW90bnNlS2pZdjJCZDlPdkhmcEt4V09XCjJPVmRwNU5xZ01YdWtWVTY2TFZ4UmpQMmhRbXhKVnFaK0I4THBNNnZ5SnRhdjVwMGJDNGVvek9ia2czcENFWVAKNFp0RS9zRnBtbTN3bUFWOWFKMlVjOU5vWldtcmlUalJPUEZ0dlNZc0pYVUcrb0tvcUVMNitrOG56REN5ME11SQpucGFSb1gwNklFYzg2MkM5VHR6eHhsRXBFcmFWYnBuaStiVm5hQlJNeWRxaS9mWXE0cXBia1I2YlNXVVFZY2xyCllHMEh1THp4N2x5clhMOGw4bi9SUzMzWGJqUWp3SzlMRVp1YXROYWxhTkd3TSs4M0NkallRT29uSHkzTlo3S2wKMnpUU0tZRmg0RlFVVUNJQUwvSE96VDNPVCtucFVjeEExOUd3MVJyYlhhNlFOVDFya3l1ZEFnTUJBQUV3RFFZSgpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFNSEtPRUNELzZMcUhwUkVSa0RlYkpJMjhYRU51eVp1VzNudnFDT1RHOWhQCnlIVXBaWWFRdzkycFUyVVFGVjdjVkh2aEpINWpaVk9DMCtaSFAvZ1pzRFR2SFBXR2tkdjJKWDVvcDNIK3FtRkwKTEdCN0dpVkR1anJwRUdjVUI3MU9ZUXloYllYZ2F2S1laVTgrS01LZ29lRkxxckJlMDhqRTdKaFZTWmkyemRzTgpES25rYnBkbHpGSGRHc2RlME1LYndzN0NLUDFEU0Q2eWlnOW9DWXlrS3RIUHEvQ0RXS2VvaTFjKzg3R1pVUXIyCjlNemlteGpEOU5iN2Nkc01HSUZwYmZ4cG1BUkl0aWl3Vjg3engyQy8zYVFVMXQzWW1nZStpM3JpL3EyMEtPODMKK2tYMzNEMkFTeUR5aUVMWlovQ29sR1FQM1l0bTdBZE9qSk9NWUVLTDA5TT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: ["ambient.ai"]
    apiVersions: ["v1alpha1"]
    resources: ["sessions"]
  admissionReviewVersions: ["v1", "v1beta1"]
  failurePolicy: Fail
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionWebhook
metadata:
  name: namespacepolicy-validation
spec:
  clientConfig:
    service:
      name: ambient-webhook-service
      namespace: ambient-system
      path: "/validate-policy"
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURIRENDQWdRQ0NRQzcwYnNIa0xmMldUQU5CZ2txaGtpRzl3MEJBUXNGQURCUU1Rc3dDUVlEVlFRR0V3SlYKVXpFTE1Ba0dBMVVFQ0F3Q1EwRXhDekFKQmdOVkJBY01BbE5HTVJJd0VBWURWUVFKREFsQmJXSnBaVzUwUVVreApFekFSQmdOVkJBTU1DbmRsWW1odmIyc3RZMkV3SGhjTk1qVXdPVEUwTWpFd09UUXhXaGNOTWpZd09URTBNakV3Ck9UUXhXakJRTVFzd0NRWURWUVFHRXdKVlV6RUxNQWtHQTFVRUNBd0NRMEV4Q3pBSkJnTlZCQWNNQWxOR01SSXcKRUFZRFZRUUtEQWxCYldKcFpXNTBRVWt4RXpBUkJnTlZCQU1NQ25kbFltaHZiMnN0WTJFd2dnRWlNQTBHQ1NxRwpTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFERjdBOWFTNDR4aW90bnNlS2pZdjJCZDlPdkhmcEt4V09XCjJPVmRwNU5xZ01YdWtWVTY2TFZ4UmpQMmhRbXhKVnFaK0I4THBNNnZ5SnRhdjVwMGJDNGVvek9ia2czcENFWVAKNFp0RS9zRnBtbTN3bUFWOWFKMlVjOU5vWldtcmlUalJPUEZ0dlNZc0pYVUcrb0tvcUVMNitrOG56REN5ME11SQpucGFSb1gwNklFYzg2MkM5VHR6eHhsRXBFcmFWYnBuaStiVm5hQlJNeWRxaS9mWXE0cXBia1I2YlNXVVFZY2xyCllHMEh1THp4N2x5clhMOGw4bi9SUzMzWGJqUWp3SzlMRVp1YXROYWxhTkd3TSs4M0NkallRT29uSHkzTlo3S2wKMnpUU0tZRmg0RlFVVUNJQUwvSE96VDNPVCtucFVjeEExOUd3MVJyYlhhNlFOVDFya3l1ZEFnTUJBQUV3RFFZSgpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFNSEtPRUNELzZMcUhwUkVSa0RlYkpJMjhYRU51eVp1VzNudnFDT1RHOWhQCnlIVXBaWWFRdzkycFUyVVFGVjdjVkh2aEpINWpaVk9DMCtaSFAvZ1pzRFR2SFBXR2tkdjJKWDVvcDNIK3FtRkwKTEdCN0dpVkR1anJwRUdjVUI3MU9ZUXloYllYZ2F2S1laVTgrS01LZ29lRkxxckJlMDhqRTdKaFZTWmkyemRzTgpES25rYnBkbHpGSGRHc2RlME1LYndzN0NLUDFEU0Q2eWlnOW9DWXlrS3RIUHEvQ0RXS2VvaTFjKzg3R1pVUXIyCjlNemlteGpEOU5iN2Nkc01HSUZwYmZ4cG1BUkl0aWl3Vjg3engyQy8zYVFVMXQzWW1nZStpM3JpL3EyMEtPODMKK2tYMzNEMkFTeUR5aUVMWlovQ29sR1FQM1l0bTdBZE9qSk9NWUVLTDA5TT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: ["ambient.ai"]
    apiVersions: ["v1alpha1"]
    resources: ["namespacepolicies"]
  admissionReviewVersions: ["v1", "v1beta1"]
  failurePolicy: Fail