apiVersion: apps/v1
kind: Deployment
metadata:
  name: ambient-webhook
  namespace: ambient-system
  labels:
    app: ambient-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ambient-webhook
  template:
    metadata:
      labels:
        app: ambient-webhook
    spec:
      serviceAccountName: ambient-webhook
      containers:
      - name: webhook
        image: localhost/ambient-webhook:v7
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: webhook-api
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ambient-webhook-service
  namespace: ambient-system
  labels:
    app: ambient-webhook
spec:
  ports:
  - name: webhook
    port: 80
    targetPort: 8080
  selector:
    app: ambient-webhook