apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backend-api
rules:
# ServiceAccounts (only for updating last-used annotations on access keys)
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get", "patch"]


